### ISSUE TITLE
Position of text feels offset compared to normal entities position

### ISSUE THREAD

**Issue by masterofshapes** [bryik/aframe-bmfont-text-component#14]
If I create a basic cube and place it at position="0 0 -5" and then do the same thing with a bmfont-text element and adjust its position to the same position="0 0 -5" and add align:center the text is not perfectly in the center of the cube as would be assumed.   I've tried other alignments as well and all shift the text to the right of the cube. Adding position = "-2 0 -5" compensates for the offset but if I change my text or make it longer I have to readjust that offset on position.x  

I guess my question is, is there a defined offset that I can just input to compensate for this shift or what would be the best way to center text in front of a camera that is located at "0 0 0" 

Thanks

**Comment by bryik** [comment]
Just from looking at in a [CodePen](https://codepen.io/bryik/pen/YGZkwX), I think the alignment property aligns text relative to the dimensions of an invisible textbox (with width set by the width property). The pivot point appears to be at the bottom left, rather than the center. This does seem unexpected considering the box primitive's pivot point is at the center. 

I may try to change this at some point.

**Comment by jpatrickpark** [comment]
Fixing this will enable nicely displaying text on objects, so I am looking forward to this happening!

**Comment by impronunciable** [comment]
This will allow me to finish implementing a full coordinate system in gurivr.com
let me know if I can help

**Comment by bryik** [comment]
Currently buried in assignments and exams...so it's a matter of time rather than will.

If anyone would like to take a stab at fixing this, PRs are welcome!

**Comment by bryik** [comment]
Closing as this issue has been open for quite some time and I'm about to archive this project.

Hopefully A-Frame's built-in text component solved these issues!
